name: ortung
channels:
  - conda-forge
dependencies:
  - python=3.8.1
  - openjdk=11.0.1
  - maven=3.6.0
  - graphviz
  - python-graphviz
  - qgrid
  - ipyvuetify
  - voila
  - pyyaml
  - pip
  - pip:
    - halo
    - virtualenv
