#!/bin/bash

# Import workspace into JupyterLab.
jupyter lab workspaces import binder/workspace.json

# Install JupyterLab support for voila.
jupyter labextension install @jupyter-voila/jupyterlab-preview

# Install ORT.
# Temporarily disabled for suspicious build/launch errors.
# git clone https://github.com/heremaps/oss-review-toolkit.git
# cd oss-review-toolkit
# ./gradlew installDist
# ./cli/build/install/ort/bin/ort --version
