#!/bin/bash

# Import workspace into JupyterLab.
jupyter lab workspaces import binder/workspace.json

# qgrid
jupyter nbextension enable --py --sys-prefix qgrid
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install qgrid2

# Install JupyterLab widgets/manager.
jupyter labextension install @jupyter-widgets/jupyterlab-manager

# Install JupyterLab support for voila.
jupyter labextension install @jupyter-voila/jupyterlab-preview

# Install ORT.
git clone https://github.com/heremaps/oss-review-toolkit.git
cd oss-review-toolkit
./gradlew installDist
./cli/build/install/ort/bin/ort --version
